---
- name: create a directory
  hosts: test-db.server
  tasks:
    - name: create directory folder
      file: path=/home/boma/folder state=directory 
    - name: copy test2 file to remote machine
      copy: src=/home/boma/test2 dest=/home/boma/folder

