---
- name: create a directory
  hosts: all
  tasks:
    - name: create directory realman
      file: path=/home/boma/realman state=directory 
    - name: copy test2 file to remote machine
      copy: src=/home/boma/test2 dest=/home/boma/realman

